const lines = [
  'FR-SPELL Help',
  '============',
  '',
  'Create predictor:',
  "  import { FrSpell } from 'fr-spell';",
  '  const predictor = await FrSpell();',
  '',
  'API methods:',
  '  lemma(input)',
  '  nounDerive(lemma, person)',
  '  adjeDerive(lemma, person)',
  '  verbDerive(lemma, person, mode, tense)',
  '  derive(lemma, wordType, person, mode, tense)',
  '',
  'Parameter descriptions:',
  '  input : inflected or conjugated surface form (example: mangeons)',
  '  lemma : base form (example: manger)',
  '  wordType : NOUN | ADJE | VERB',
  '  mode/tense : only needed for verbDerive and derive with wordType=VERB',
  '',
  'Allowed person values:',
  '  FST (1st person singular)',
  '  SND (2nd person singular)',
  '  THD_M (3rd person masculine singular)',
  '  THD_F (3rd person feminine singular)',
  '  FST_PL (1st person plural)',
  '  SND_PL (2nd person plural)',
  '  THD_PLM (3rd person masculine plural)',
  '  THD_PLF (3rd person feminine plural)',
  '',
  'Allowed mode values:',
  '  INDI (indicative)',
  '  SUBJ (subjunctive)',
  '  COND (conditional)',
  '  PART (participle)',
  '  IMPE (imperative)',
  '  INFI (infinitive)',
  '',
  'Supported tense values in this implementation:',
  '  PRES (present), IMPA (imperfect), FUTU (future), PASS (past)',
  '',
  'Notes:',
  '  - noun/adje derive do not require mode or tense in user input',
  '  - for verbs, use one of PRES/IMPA/FUTU/PASS in tense',
  '',
  'Examples:',
  "  await predictor.lemma('mangeons');",
  "  await predictor.nounDerive('chat', 'THD_PLF');",
  "  await predictor.adjeDerive('beau', 'THD_F');",
  "  await predictor.verbDerive('manger', 'FST_PL', 'INDI', 'PRES');",
];

console.log(lines.join('\n'));
